In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
scalar = tf.constant(7)
scalar
# Creating a scalar using tf.constant()

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions (ndim)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimensions
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimensions)
matrix = tf.constant([[1,2],
                      [2,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

In [7]:
# Check the dimension
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[1.1,3.14],
                              [10., 7.],
                              [8., 9.]], dtype=tf.float16) ## Specifying the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 1.1 ,  3.14],
       [10.  ,  7.  ],
       [ 8.  ,  9.  ]], dtype=float16)>

In [9]:
# What's the number of dimensions of another_matrix?
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       
                       [[7,8,9],
                        [10,11,12]],
                       
                       [[13,14,15],
                        [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
# Check it's dimension
tensor.ndim

3

What we've created so far
* Scalar: a single number
* Vector: a number with a direction
* Matrix: a 2-dimensional array of numbers
* Tensorr: a n-dimensional array of numbers (when n can be any number: a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector and so on)

### Creating tensor with tf.Variable

In [12]:
# Create a tensor using tf.Variable() -- changable tensor

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# # Lets try changing one element of the  changable tensor
# changeable_tensor[0] = 7
# changeable_tensor   #gives error

In [14]:
# Lets try changing one element of the  changable tensor using .assign()

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# # Lets try changing one element of the unchangable tensor using .assign()

# unchangeable_tensor[0].assign(7)
# unchangeable_tensor  # gives error

🔑 **Note:** Rarely in practice we would need to decide for ourselves if we need tf.constant or tf.Variable. Tensorflow does that for us. But if in doubt, use tf.constant and change it later if need be

## Creating Random Tensors

Random tensors are tensors of some arbitrary size with some random numbers

In [16]:
# Createing random tensors

In [17]:
random_1 =tf.random.Generator.from_seed(42)  # set seed for redproducibility
random_1 = random_1.normal(shape=(3,2))
random_1  ## Pulls out numbers from a normal distribution

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [18]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(3,2))
random_2  ## Pulls out numbers from a uniform distribution

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

### Shuffling the order of elements in a tensor

In [19]:
# Shuffle a tensor (valuable for when you wwant to shuffle your data so that the inherent data doesn't affect the learning)
not_shuffled = tf.constant([
                            [1,2],
                            [3,4],
                            [5,6]
])
not_shuffled.ndim

2

In [20]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [21]:
## Shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled)  ## Shuffles along its first dimension
## gives a different order everytime

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [22]:
tf.random.set_seed(42)  ## global level seed

tf.random.shuffle(not_shuffled)  ## Shuffles along its first dimension
## Seed is set beforehand

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [23]:
tf.random.shuffle(not_shuffled, seed=42)  ## Shuffles along its first dimension
## Seed is set beforehand // operation level seed
## still gives the shuffled order everytime different

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [24]:
tf.random.set_seed(2)  ## global level seed

tf.random.shuffle(not_shuffled, seed=42)  ## Shuffles along its first dimension
## Seed is set beforehand

## random oreder is geerated but this order is preserved

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [25]:
tf.random.set_seed(2)  ## global level seed

tf.random.shuffle(not_shuffled, seed=2)  ## Shuffles along its first dimension
## Seed is set beforehand

## random oreder is geerated but this order is preserved

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

🔑 **Note:** If we want our shuffled tensors to have a preserved order, then set both the gloal level and operation level seed

## Other ways to make tensors

In [26]:
tf.ones([10,])


<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [27]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [28]:
tf.zeros((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [29]:
tf.zeros(shape=[3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays and tensors

The main difference between tensor and numpy is that a tensor can be run on a GPU for numerical computing

In [30]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [31]:
A = tf.constant(numpy_A)  ## Numpy array to a tensor
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [32]:
B = tf.constant(numpy_A, shape=(3,2,4))
B

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Getting informations from Tensors

In [33]:
A.ndim, B.ndim ## Dimensions of a tensors

(1, 3)

Most important informations
* Shape              tensor.shape
* Rank               tensor.ndim
* Axis or dimension  tensor[0],tensor[: , 1]
* Size               tf.size(tensor)

In [34]:
# Create a rank 4 tensor
# that is 4 dimensions

rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [36]:
rank_4_tensor[0].ndim

3

In [37]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [38]:
2*3*4*5

120

In [39]:
# Get various attributes of our tensor
print("Data type of every element: \t", rank_4_tensor.dtype)
print("Number of dimensions (rank): \t", rank_4_tensor.ndim)
print("Shape of the tensor: \t", rank_4_tensor.shape)
print("Elements along the 0 axis: \t", rank_4_tensor[0])
print("Elements along the last axis: \t", rank_4_tensor[-1])
print("Total elements in our tensor: \t", tf.size(rank_4_tensor))

Data type of every element: 	 <dtype: 'float32'>
Number of dimensions (rank): 	 4
Shape of the tensor: 	 (2, 3, 4, 5)
Elements along the 0 axis: 	 tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Elements along the last axis: 	 tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Total elements in our tensor: 	 tf.Tensor(120, shape=(), dtype=int32)


In [40]:
print("Data type of every element: \t", rank_4_tensor.dtype)
print("Number of dimensions (rank): \t", rank_4_tensor.ndim)
print("Shape of the tensor: \t\t", rank_4_tensor.shape)
print("Elements along the 0 axis: \t", rank_4_tensor.shape[0])
print("Elements along the last axis: \t", rank_4_tensor.shape[-1])
print("Total elements in our tensor: \t", tf.size(rank_4_tensor).numpy())  ## to remove the extra output from tensorflow

Data type of every element: 	 <dtype: 'float32'>
Number of dimensions (rank): 	 4
Shape of the tensor: 		 (2, 3, 4, 5)
Elements along the 0 axis: 	 2
Elements along the last axis: 	 5
Total elements in our tensor: 	 120


### Indexing tensors

Tensors can be indexed just like python lists

In [41]:
# Get the first 2 elements of each dimension just like python lists

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [42]:
# get the first element from each dimension from each index except from the last index

rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [43]:
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [44]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [45]:
# Create a rank 2 tensor (2 dimension)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor, rank_2_tensor.ndim, rank_2_tensor.shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>, 2, TensorShape([2, 2]))

In [46]:
# Get the last item of each row of our rank 2 tensor

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [47]:
# Add in extra dimension to our rank 2 tensor

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [48]:
rank_3_tensor_replica = rank_2_tensor[:,:, tf.newaxis] # instead of ...
rank_3_tensor_replica

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [49]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [50]:
# Expanding the zero axis

tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [51]:
# Expanding the middle axis

tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

## Manipulating Tensor (Tensor operations)

**Basic Operation**

`+` , `-` , `*` , `/`

In [52]:
# Addition

tensor = tf.constant([[10, 7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [53]:
tensor ## Tensor remains unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [54]:
# Multiplication

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [55]:
# Substraction

tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [56]:
# We can use the tensorflow built in function too

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

 ## Matrix Multiplication

 In ML, matrix multiplication is one of the most common tensor operations

In [57]:
 # MAtrix multiplication in tensorflow

print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [58]:
tensor * tensor  # this is element wise multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [59]:
tensor @ tensor  # python matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [60]:
# Create a tensor of shape 3,2

X= tf.constant([[1,2],
                [3,4],
                [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [61]:
# tf.matmul(X, Y), X @ Y  ## Gives error of incompatible matricx size

Rule for matrix multiplication
1. Inner dimensions must match
2. (a,b) and (b,c) can be multiplied to result as (a,c)

In [62]:
# Let's change the shape of Y
tf.reshape(Y, [2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [63]:
X @ tf.reshape(Y, [2,3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [64]:
tf.matmul(X, tf.reshape(Y, [2,3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [65]:
tf.reshape(Y, [2,3]) @ X  # reshaping X instead of Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 76, 100],
       [103, 136]], dtype=int32)>

In [66]:
# Can do the same with transpose -- I mean matrix multiploication

X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [67]:
# Try matrix multilication with transpose instead of reshape

tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

 ## The dot product

 Matrix multiplication is also called dot product

 * tf.matmul()
 * tf.tensordot()

In [68]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [69]:
# Perform dot product on X and Y -- This will require us to transpose

tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [70]:
# Perform matrix multiplication with Y transpose

tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [71]:
# Perform matrix multiplication with Y reshaped

tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [72]:
# check the values of Y, reshape Y and transposed Y

print("Normal Y:")
print(Y, "\n")

print("Reshaped Y:")
print(tf.reshape(Y, shape=(2,3)), "\n")

print("Transposed Y:")
print(tf.transpose(Y), "\n")

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Reshaped Y:
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



Generally when performing matrix multiplication, and one of the axes is incorrect, we would transpose, more often and more generally, than use reshape

## Changing the data Type of a tensor

In [73]:
# Create a new tensor with default data type (float32) -- It actually depends upon the type of data being passed

B = tf.constant([1.7, 4.6])
B.dtype

tf.float32

In [74]:
C = tf.constant([1,2])
C.dtype

tf.int32

In [75]:
D = tf.constant(["AA", "BB"])
D

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'AA', b'BB'], dtype=object)>

In [76]:
# Change datatype from float32 to float16

D = tf.cast(B, dtype=tf.float16)
D , D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 4.6], dtype=float16)>,
 tf.float16)

In [77]:
# Change from int32 to float32

E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [78]:
F = tf.cast(B, dtype=tf.int32)
F

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

## Aggregating tensors

Aggregating tensors is condensing them from multiple values down to a smaller amounts of values

In [79]:
# Get the absolute values

D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [80]:
#Get the absolute values

tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregation
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [81]:
 # Create a random tensor with values betweem 0 and 100 of size 50

 E = tf.constant(np.random.randint(0,100,size=50))
 E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 1, 30,  9, 18, 38, 64, 49, 34, 87, 83, 49, 16, 19, 50, 43, 78, 57,
       69, 13, 58, 21, 61, 42, 42,  4, 16, 16, 66, 93, 76, 51, 70, 94, 80,
       99, 68, 92, 77, 49, 92, 51, 75, 32, 74, 34, 68,  2, 55,  6,  3])>

In [82]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [83]:
# get the Minimum

tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [84]:
np.min(E) ## Another way, using numpy

1

In [85]:
# Find the maximum

tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [86]:
# Find the mean

tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [87]:
# Find the sum

tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2474>

### Find the variance and standard deviation of a tensor

In [88]:
# To find the variance of a tensor we need access to tensorflow_probability

import tensorflow_probability as tfp
tfp.stats.variance(E), tfp.stats.variance(E).numpy()

(<tf.Tensor: shape=(), dtype=int64, numpy=809>, 809)

In [89]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=808.80963>

In [90]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))  ## It doesnt take integer arguments

<tf.Tensor: shape=(), dtype=float32, numpy=28.439579>

In [91]:
tfp.stats.stddev(tf.cast(E, dtype=tf.float32))  ## Amother way
## It doesnt take integer arguments

<tf.Tensor: shape=(), dtype=float32, numpy=28.439579>

### Find the positional maximum or minimum



In [92]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [93]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [94]:
# Index on our largest value position

F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [95]:
# Find the maximum value of tensor

tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [96]:
tf.reduce_max(F) == F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [97]:
# Find the positional minimum

tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [98]:
# Find the minimum value using positional minimum index

F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Sequeezing a tensor (Removing all single dimensions)

In [99]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G 

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [100]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [101]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

## One-hot encoding

In [102]:
# Create a list of indices 

some_list = [0, 1, 2, 3, 2, 1] # Could be red , blue green and yellow

# One hot encode our list
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]], dtype=float32)>

In [103]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="Gangar", off_value="Alakazam")

<tf.Tensor: shape=(6, 4), dtype=string, numpy=
array([[b'Gangar', b'Alakazam', b'Alakazam', b'Alakazam'],
       [b'Alakazam', b'Gangar', b'Alakazam', b'Alakazam'],
       [b'Alakazam', b'Alakazam', b'Gangar', b'Alakazam'],
       [b'Alakazam', b'Alakazam', b'Alakazam', b'Gangar'],
       [b'Alakazam', b'Alakazam', b'Gangar', b'Alakazam'],
       [b'Alakazam', b'Gangar', b'Alakazam', b'Alakazam']], dtype=object)>

## Squaring, log and square root

In [104]:
# Create a new tensor

H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [105]:
# Square tensor H

tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [106]:
# Square root tensor H

tf.math.sqrt(tf.cast(H, dtype=tf.float32))  ## Will give error with integer data

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [107]:
# Find the log of tensor H

tf.math.log(tf.cast(H, dtype=tf.float32))  ## Will give error with integer data

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and NumPy


Tensorflow interacts beautifully with numpy array

In [109]:
# Create a tensr directly from numpy array

J = tf.constant(np.array([3.,7.,10.,4.]))
J

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 3.,  7., 10.,  4.])>

In [110]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.,  4.]), numpy.ndarray)

In [111]:
# Convert Tensor J  to numpy array

J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.,  4.]), numpy.ndarray)

In [114]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [116]:
# The default types of each are different

numpy_J = tf.constant(np.array([1.,2.,3.]))
tensor_J = tf.constant([1.,2.,3.])

numpy_J.dtype, tensor_J.dtype   ## The deafault dtype of tensors formed from numpy is float64
                                ## While that formed from a general python list is float32

(tf.float64, tf.float32)